EXERCISES = [
    
    {
        "name": "Barbell Bench Press",
        "description": "A compound horizontal pushing exercise targeting the chest.",
        "primary_muscle": "Chest",
        "equipment": "Barbell",
        "tracking_type": "reps_weight",
    },
    {
        "name": "Incline Barbell Bench Press",
        "description": "A pressing exercise emphasizing the upper portion of the chest.",
        "primary_muscle": "Chest",
        "equipment": "Barbell",
        "tracking_type": "reps_weight",
    },
    {
        "name": "Dumbbell Bench Press",
        "description": "A dumbbell pressing exercise targeting the chest.",
        "primary_muscle": "Chest",
        "equipment": "Dumbbell",
        "tracking_type": "reps_weight",
    },
    {
        "name": "Incline Dumbbell Press",
        "description": "A pressing exercise emphasizing the upper chest.",
        "primary_muscle": "Chest",
        "equipment": "Dumbbell",
        "tracking_type": "reps_weight",
    },
    {
        "name": "Cable Chest Fly",
        "description": "An isolation exercise targeting the chest using a cable machine.",
        "primary_muscle": "Chest",
        "equipment": "Cable",
        "tracking_type": "reps_weight",
    },

    {
        "name": "Barbell Squat",
        "description": "A compound lower-body exercise primarily targeting the quadriceps.",
        "primary_muscle": "Quadriceps",
        "equipment": "Barbell",
        "tracking_type": "reps_weight",
    },
    {
        "name": "Leg Press",
        "description": "A machine-based compound exercise targeting the lower body.",
        "primary_muscle": "Quadriceps",
        "equipment": "Machine",
        "tracking_type": "reps_weight",
    },
    {
        "name": "Leg Extension",
        "description": "An isolation exercise targeting the quadriceps.",
        "primary_muscle": "Quadriceps",
        "equipment": "Machine",
        "tracking_type": "reps_weight",
    },
    {
        "name": "Romanian Deadlift",
        "description": "A hip-hinge exercise primarily targeting the hamstrings.",
        "primary_muscle": "Hamstrings",
        "equipment": "Barbell",
        "tracking_type": "reps_weight",
    },
    {
        "name": "Leg Curl",
        "description": "An isolation exercise targeting the hamstrings.",
        "primary_muscle": "Hamstrings",
        "equipment": "Machine",
        "tracking_type": "reps_weight",
    },

    {
        "name": "Barbell Deadlift",
        "description": "A compound pulling exercise involving the posterior chain.",
        "primary_muscle": "Back",
        "equipment": "Barbell",
        "tracking_type": "reps_weight",
    },
    {
        "name": "Lat Pulldown",
        "description": "A vertical pulling exercise targeting the back.",
        "primary_muscle": "Back",
        "equipment": "Cable",
        "tracking_type": "reps_weight",
    },
    {
        "name": "Seated Cable Row",
        "description": "A horizontal pulling exercise targeting the back.",
        "primary_muscle": "Back",
        "equipment": "Cable",
        "tracking_type": "reps_weight",
    },
    {
        "name": "Barbell Row",
        "description": "A compound horizontal pulling exercise targeting the back.",
        "primary_muscle": "Back",
        "equipment": "Barbell",
        "tracking_type": "reps_weight",
    },

    {
        "name": "Overhead Press",
        "description": "A compound vertical pressing exercise targeting the shoulders.",
        "primary_muscle": "Shoulders",
        "equipment": "Barbell",
        "tracking_type": "reps_weight",
    },
    {
        "name": "Dumbbell Shoulder Press",
        "description": "A dumbbell vertical pressing exercise targeting the shoulders.",
        "primary_muscle": "Shoulders",
        "equipment": "Dumbbell",
        "tracking_type": "reps_weight",
    },
    {
        "name": "Lateral Raise",
        "description": "An isolation exercise targeting the lateral deltoids.",
        "primary_muscle": "Shoulders",
        "equipment": "Dumbbell",
        "tracking_type": "reps_weight",
    },

    {
        "name": "Barbell Curl",
        "description": "An isolation exercise targeting the biceps.",
        "primary_muscle": "Biceps",
        "equipment": "Barbell",
        "tracking_type": "reps_weight",
    },
    {
        "name": "Dumbbell Curl",
        "description": "An isolation exercise targeting the biceps.",
        "primary_muscle": "Biceps",
        "equipment": "Dumbbell",
        "tracking_type": "reps_weight",
    },

    {
        "name": "Tricep Pushdown",
        "description": "An isolation exercise targeting the triceps.",
        "primary_muscle": "Triceps",
        "equipment": "Cable",
        "tracking_type": "reps_weight",
    },
    {
        "name": "Dumbbell Overhead Tricep Extension",
        "description": "An isolation exercise targeting the triceps.",
        "primary_muscle": "Triceps",
        "equipment": "Dumbbell",
        "tracking_type": "reps_weight",
    },

    {
        "name": "Standing Calf Raise",
        "description": "An exercise targeting the calf muscles.",
        "primary_muscle": "Calves",
        "equipment": "Machine",
        "tracking_type": "reps_weight",
    },
    {
        "name": "Bodyweight Calf Raise",
        "description": "A bodyweight exercise targeting the calves.",
        "primary_muscle": "Calves",
        "equipment": "Bodyweight",
        "tracking_type": "reps",
    },

    {
        "name": "Plank",
        "description": "A bodyweight isometric exercise targeting the core.",
        "primary_muscle": "Core",
        "equipment": "Bodyweight",
        "tracking_type": "duration",
    },
    {
        "name": "Hanging Leg Raise",
        "description": "A bodyweight exercise targeting the abdominal muscles.",
        "primary_muscle": "Core",
        "equipment": "Bodyweight",
        "tracking_type": "reps",
    },
    
]